export const GET_TASKS = "GET_TASKS";
export const CREATE_TASK = "CREATE_TASK";
export const UPDATE_TASK = "UPDATE_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const UPDATE_TASKS_STATUS = "UPDATE_TASKS_STATUS";

export const GET_PROJECTS = "GET_PROJECTS";
export const CREATE_PROJECT = "CREATE_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT"; 
export const DELETE_PROJECT = "DELETE_PROJECT";

export const GET_PROJECT_POINTS = "GET_PROJECT_POINTS";
export const CREATE_PROJECT_POINTS = "CREATE_PROJECT_POINTS";
export const UPDATE_PROJECT_POINTS = "UPDATE_PROJECT_POINTS";